import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { Dispatcher, TeamStats, Win } from "./StatsPanel";

// Brand palette (print-friendly: dark ink on white, accent for highlights).
const INK: [number, number, number] = [16, 23, 40];
const MUTED: [number, number, number] = [110, 122, 143];
const ACCENT: [number, number, number] = [99, 102, 241];
const HAIRLINE: [number, number, number] = [224, 230, 240];

const MARGIN = 48;

function timeSaved(w: Win): string {
  const totalMin = Math.floor(((w.emailsSent + w.mapsOpened + w.callsPlaced) * 30) / 60);
  const h = Math.floor(totalMin / 60);
  const m = totalMin % 60;
  if (h <= 0) return `${m}m`;
  if (m === 0) return `${h}h`;
  return `${h}h ${m}m`;
}

function sum(wins: Win[]): Win {
  return wins.reduce(
    (a, w) => ({
      emailsSent: a.emailsSent + w.emailsSent,
      mapsOpened: a.mapsOpened + w.mapsOpened,
      callsPlaced: a.callsPlaced + w.callsPlaced,
    }),
    { emailsSent: 0, mapsOpened: 0, callsPlaced: 0 }
  );
}

function section(doc: jsPDF, title: string, pick: (d: Dispatcher) => Win, stats: TeamStats, y: number): number {
  // Keep the section label with its table: start a new page if too close to the bottom.
  if (y > doc.internal.pageSize.getHeight() - 140) {
    doc.addPage();
    y = 64;
  }

  doc.setFont("helvetica", "bold").setFontSize(12).setTextColor(...INK);
  doc.text(title, MARGIN, y);

  const wins = stats.dispatchers.map(pick);
  const total = sum(wins);

  autoTable(doc, {
    startY: y + 10,
    head: [["Dispatcher", "Emails", "Maps", "Calls", "Time saved"]],
    body: [
      ...stats.dispatchers.map((d, i) => [
        d.email,
        String(wins[i].emailsSent),
        String(wins[i].mapsOpened),
        String(wins[i].callsPlaced),
        timeSaved(wins[i]),
      ]),
      ["Whole team", String(total.emailsSent), String(total.mapsOpened), String(total.callsPlaced), timeSaved(total)],
    ],
    margin: { left: MARGIN, right: MARGIN },
    theme: "grid",
    styles: { font: "helvetica", fontSize: 10, cellPadding: 6, textColor: INK, lineColor: HAIRLINE, lineWidth: 0.5 },
    headStyles: { fillColor: INK, textColor: 255, fontStyle: "bold" },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { halign: "right" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right", textColor: ACCENT },
    },
    didParseCell: (data) => {
      // Bold the "Whole team" totals row.
      if (data.section === "body" && data.row.index === stats.dispatchers.length) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [244, 246, 252];
      }
    },
  });

  return (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 30;
}

export function buildTeamReportDoc(stats: TeamStats, generatedAt: Date): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const dateStr = generatedAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  // Header
  doc.setFont("helvetica", "bold").setFontSize(18).setTextColor(...INK);
  doc.text("TRUCK", MARGIN, 60);
  doc.setTextColor(...ACCENT);
  doc.text("BOX", MARGIN + doc.getTextWidth("TRUCK"), 60);

  doc.setFontSize(24).setTextColor(...INK);
  doc.text("Team Performance Report", MARGIN, 96);

  doc.setFont("helvetica", "normal").setFontSize(11).setTextColor(...MUTED);
  doc.text(`${stats.organizationName}  ·  ${stats.seats} seats  ·  ${dateStr}`, MARGIN, 114);

  doc.setDrawColor(...HAIRLINE).setLineWidth(1);
  doc.line(MARGIN, 128, pageW - MARGIN, 128);

  let y = 158;
  y = section(doc, "This week", (d) => d.weekToDate, stats, y);
  y = section(doc, "This month", (d) => d.monthToDate, stats, y);
  section(doc, "All time", (d) => d.total, stats, y);

  // Footer with page numbers on every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(...MUTED);
    doc.text("Generated by TruckBox  ·  truckbox.app", MARGIN, h - 30);
    doc.text(`${i} / ${pages}`, pageW - MARGIN, h - 30, { align: "right" });
  }

  return doc;
}

export function downloadTeamReportPdf(stats: TeamStats): void {
  const now = new Date();
  const doc = buildTeamReportDoc(stats, now);
  doc.save(`truckbox-team-report-${now.toISOString().slice(0, 10)}.pdf`);
}
